name: 'CDK'

on:
  pull_request:
    paths:
      - 'bin/**'
      - 'lib/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  cdk-synth:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18] 

    steps:
      - uses: actions/checkout@v2
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://npm.pkg.github.com'
      - run: 'npm ci'
        env:
          CDK_DEFAULT_ACCOUNT: 492839121
      - run: 'npm run cdk synth'
      - run: 'npm run test-cdk'
